'''
yazan : nAİm
16.10.2025
    bu ilk ödevim kodlarimin amaci herhangi bir metindeki en çok tekrar eden kelimeleri
    bulmak.
'''

if __name__ == "__main__":
 from collections import Counter
 import re

# metni buraya yazabilirsin
 metin = """
1. Giriş

Mustafa Kemal, birikim, deneyim, bilinç ve özlemlerle bağımsızlaşma, çağdaşlaşma eylemine girişmiştir (Kili 2000: 165). Atatürk, ileriyi ve gerçeği gören özelliğiyle hem eylemi, hem de ülküleri olan, kendi dönemi içinde yarattığı devrimi en iyi anlayan, anlatan, en iyi yorumlayan ve yarattığı devrimin en iyi düşünürüdür. O, bağımsızlık hareketini zaferle neticelendirdikten sonra başlattığı çağdaşlaşma hareketini kısa bir sürede başarıya ulaştırmıştır (Kili 2000: 175). Mustafa Kemal’in böyle bir çağdaşlaşma hamlesini kısa bir sürede başarıya ulaştırmış olmasında, inkılâba dair düşünce ve ideallerini daha evvelden bir sistem dâhilinde tasarlaması yatmaktadır.

Mustafa Kemal’de inkılâp fikrinin doğuşu meselesi, Atatürk ve Türkiye Cumhuriyeti tarihi açısından son derece büyük öneme haizdir. Onun siyasî, iktisadî, sosyal ve kültürel inkılâpları, bir düzen, bir plan dâhilinde gerçekleştirmiş olmasını, Mustafa Kemal’de inkılâp düşüncesi ve idealinin daha önceden var olmasında aramalıyız. Mustafa Kemal’de inkılâp fikrini çocukluk ve gençlik yıllarına kadar götürebiliriz. Kişinin gelişme ve olgunlaşmasında yaşadığı çevre, karşılaştığı kişiler, olaylar ile fikirler önemli etkenlerdir. Mustafa Kemal’in yaşadığı coğrafya ve çağ, içinde bulunduğu sosyal çevre, kişiler, okuduğu kitaplar ve okullar, daima onu düşünmeye ve bir şeyler yapmaya sevk etmiştir. İşte, bütün bu saydığımız etkenler ile onun doğuştan getirmiş olduğu üstün nitelikleri, edindiği tecrübeleri ve bilgi birikimi, Mustafa Kemal’de inkılâp düşüncesi ve idealinin oluşmasına yol açmıştır.

Mustafa Kemal’i yoğuran fikir hareketleri nelerdi? Mustafa Kemal kimleri ve neleri okumuş, kafasını nasıl hazırlamıştı? Bu sorular, onun fikir hayatının oluşmasının temel dinamiklerini ortaya koymak açısından önemlidir.

Kişilerin fikir hayatının gelişiminde önemli olan başlıca unsurlar; kişinin doğuştan getirdiği özellikler, aile ve çevresi, doğup büyüdüğü şehrin sosyokültürel vasfı, eğitim ve meslek hayatı, okuduğu kitaplar, fikir ve perspektif açısından yön verebilecek kişiler, düşünürler ve fikir adamları, yaşadığı çağ ve olaylardır. Mustafa Kemal’de inkılâp fikri ve idealinin gelişmesini bu çerçevede ele alarak konuya açıklık getirmeye çalışacağız.

2. Mustafa Kemal’de İnkılâp Düşüncesinin Oluşumu ve Gelişiminde Rol Oynayan Faktörler

Osmanlı devletinin siyasî, idarî, iktisadî, askerî ve eğitim ile diğer toplumsal problemlerine çare bulmak maksadıyla 17. yüzyıldan itibaren başlatılan yenilik ve değişim hareketleri ve bunu gerçekleştirmek için meydana gelen düşünce akımlarının, yeni devletin kurulması için gerekli deneyimi sağladığı ifade edilebilir (Lewis 1977: 15-22). Osmanlı devletinde yüzyılı aşkın bir süredir devam eden yenileşme sürecinin, Mustafa Kemal’de inkılâp fikirlerinin gelişimine büyük katkı sağladığı bir gerçekliktir ve bu süreç onu inkılâba hazırlamıştır (İnalcık 1998: 125-132). Mustafa Kemal, gerek Milli Mücadele gerekse Türk inkılâbı safhasını başlattığında tarihsel temellere dayanan belirli bir düşünce yapısına, siyasî görüş ve inanca sahipti (Irmak 1992: 1-34; Süslü 1995: 265-278; Baykal 1992: 243-263). Onun bu düşünsel yapıya sahip olması, Türk inkılâbının sistemli, planlı, programlı bir hareket tarzı haline gelmesini sağlamıştır.

2.1. Mustafa Kemal’de İnkılâp Fikirlerinin Gelişiminde Çocukluk ve Öğrenim Dönemi ile Yaşadığı Şehirlerin Rolü

Makedonya’ya yerleşen Türklerin son büyük evlad-ı fatihanı (Atay 1984: 18) Mustafa Kemal’de inkılâp düşüncesi, sadece ateşkes antlaşması sırasında var olan bir gerçeklik değildi. Ondaki inkılâp fikri ve ideali, okul sıralarında oluşmaya başlamıştır. Mustafa Kemal’in fikir yapısının gelişmesinde herkeste olduğu gibi ailesi, çevresi ve öğretmenleri büyük rol oynamıştır (Turan 1989: 5-6).

Kişilerin yetişmesinde şehirlerin önemi büyüktür. Mustafa Kemal’in yetişmesinde ve batılı fikirlerle ilk tanışmasında doğup büyüdüğü şehir Selanik’in önemli etkisi olmuştur. Mustafa Kemal’in idadiye kadar eğitim ve öğretimini geçirdiği Makedonya’nın en büyük şehirlerinden ve en önemli limanlarından biri olan Selanik, Osmanlı devletinin Avrupa’ya açılan kapısıydı. Türk basın hayatının oldukça canlı olduğu Selanik,1 o dönemde bütün fikirlerin serbestçe tartışılabildiği (MEB 1970: 1-6) kozmopolit bir şehirdi (Eroğlu 1982: 103-104). Çocukluğundan itibaren inkılâp fikirlerini besleyen Selanik, Mustafa Kemal’in yetişmesinde büyük etkiye sahiptir.

Bireyin yetişmesi, eğitim ve kültür kazanmasında ailenin önemi büyüktür. Mustafa Kemal’in yetişmesinde ailesinin büyük etkisi olmuştur. Mustafa Kemal’in babası Ali Rıza Efendi, batı fikirlerine açık, çağdaş düşünceye sahip bir insandı. Annesi Zübeyde Hanım ise eşine göre geleneksel düşünceye sahip bir kişiydi. Mustafa Kemal’in annesi ve babasının farklı anlayışlara sahip olması, onun yetişme hayatının şekillenmesinde önemli rol oynamıştır. Bu farklılık, Mustafa Kemal’in ilkokula başlamasında kendini hissettirmiş, babası daha modern bir eğitim veren okula göndermeyi arzu etmişken, annesi geleneksel eğitim veren bir okula yollamayı istemiştir (Yalçın 2006: 33). Neticede annesinin dediği olmuş ve 1887’de Hoca Kasımpaşa Semtindeki Fatma Molla Kadın Okuluna gönderilmiştir (Cebesoy 1967/I: 16; Borak 1973: 12).2 İlk mahalle mektebine isteyerek gitmemişti. Bu düşüncesini ileride “benim fikrimi soran olmadı” (Cebesoy 1967/I: 12-13; krş. Bayur 1963/I: 8) şeklinde ifade etmiştir. Daha sonra burada yaşadığı olumsuz bir hadiseden sonra babası Ali Rıza Efendi, onu bu mektepten alarak zamanının modern eğitim veren okulu olan Şemsi Efendi Mektebi’ne kaydettirmiştir (Yalman 1922; Cebesoy s.12; Bayur 1963/I: 8; Kinross 1966: 23).3 Bu okul, 1873 tarihinde Selanik’teki Türklerin açmış oldukları ilk özel okuldur. Çağdaş nesiller yetiştirmeyi ilke edinen okul, eğitim öğretimde usul-i tedrisat yöntemini kullanmaktaydı.4 Şemsi Efendi Mektebi, Mustafa Kemal’in öğrenim hayatının, kişiliğinin ve düşüncelerinin oluşmasında büyük rol oynamıştır (Yalçın 2006: 36).

Mustafa Kemal, Şemsi Efendi Mektebi’nin orta kısmının ikinci sınıfına gittiği esnada, 28 Kasım 1893 tarihinde babasını kaybetti (Unat 1964: 82). Babasının ölümü Mustafa Kemal’in öğrenim hayatına kısa bir süre ara vermesine neden olmuştur (Yalçın 2006: 37). Bunun üzerine Zübeyde Hanım, çocuklarını da alarak kardeşinin Langaza’daki çiftliğine gitti. Burada, Mustafa Kemal’i Rum Kilise Okuluna yollamayı düşünmüşlerse de, o bunu kabul etmemiştir (Yalçın 2006: 37). Mustafa Kemal’in Rum Kilise Okuluna gönderilme teklifini daha o yaşlarda reddetmesi oldukça dikkat çekicidir.

Daha 12 yaşında babasını kaybederek yetim kalması psikolojik açıdan, kendi geleceği hakkında yine kendisinin bağımsız, özgürce karar vermesinde etkili olmuştur. Bu durum bilim adamlarınca da kabul görmektedir. “Yetim çocuklarda gelişen güçlenme içgüdüsü çoğu kez onları amaçlarına ulaştırmaktadır” diyen İsviçreli bilim adamı Dr. Pierre Retchnick; Mustafa Kemal’in yetim kalışının kişiliği üzerindeki psikolojik etkisi üzerinde şu tespitlere yer vermiştir; “Bu konuda en güzel örnek çocuk yaşta babasını yitiren Mustafa Kemal Atatürk’tür. Kendini ülkenin yararlarına adayan Atatürk’ün bu çapta bir kişi olmasının en büyük etkenlerinden biri, babasının o küçük yaştayken ölmesidir” (Hürriyet 1978).

Mustafa Kemal’in kişiliğinin şekillenmesinde dayısının çiftliğinde geçirdiği beş aylık dönemin önemli tesiri vardır. Atatürk’te yaratıcılık, ağaç ve hayvan sevgisinin gelişiminde çocukken yaşadığı bu yaratıcı çevrenin de etkisi olmuştur (Yalçın 2006: 38).5

Yaklaşık beş ay süren bir çiftlik hayatından sonra Selanik’teki halasının yanına gönderilen Mustafa Kemal, Mülkiye Rüştiyesi’ne başladı. Burada “Kaymak Hafız” olarak bilinen matematik öğretmeni Hüseyin Efendi’nin Mustafa Kemal’i dövmesi üzerine, bunu gururuna yediremeyen büyük annesi Ayşe Hanım, onu Mülkiye Rüştiyesi’nden aldı (Unat 1964: 82-83). Büyük annesinin Mustafa Kemal’i bu okuldan alma kararı, onun geleceğinin şekillenmesi açısından verilmiş mühim bir hadise olarak değerlendirilmelidir.

Mustafa Kemal, daha çocuk yaşlarda iken asker olmayı kafasına koymuştu. Ancak ailesi onun asker olmasını istemiyordu. Balkanlarda çetecilik faaliyetleri neticesinde Türklere karşı yapılan tecavüzkâr hareketler, onda milliyetçi duyguların yer etmesine yol açmıştır. Mustafa Kemal’in yaşadığı dönemde çocuklar aralarında çetecilik ve askercilik oyunları oynamaktaydılar. Balkanlarda yaşanan sıcak gelişmeler, çocukların oyunlarına dahi aksetmiş, çocukların daha o yaşlarda millî hislerle yetişmelerine neden olmuştur. Mustafa Kemal ve akranları çocukluklarında büyüklerinden çetelerin menfi faaliyetlerini dinlemeleri onlarda asker olma isteğini ortaya çıkartmıştır.6 Mustafa Kemal ve akranlarının çocukluklarında yaşadıkları gelişmeler ileride onların askerî okullara gitmelerine neden olmuştur diyebiliriz.

Onun askerliğe karşı hevesinin artmasında, üniformalı olarak Askerî Rüştiye’ye giden komşularından Kadri Bey’in oğlu Ahmet ve sokaklarında gördüğü üniformalı subaylar da etkili olmuştur. Mustafa Kemal’in annesi onun asker olmasını istemiyordu. Annesinin karşı çıkacağını bildiğinden dolayı annesine haber vermeden Selanik Askeri Rüştiyesi’nin sınavlarına girmiş ve başarılı olmuştur (Yalçın 2006: 39; Villata 2000: 11).

Mustafa Kemal kendisine sorulmadan anne, baba ve akrabalarının isteklerine göre yönlendirildiği eğitim hayatında bu kez kimseyi dinlememiş, bizzat kendisinin kararıyla öteden beri hayalini kurduğu askerlik mesleğine ulaşmak gayesiyle ilk önce Selanik Askerî Rüştiyesi’ne girmiştir. Kendi isteğiyle kaydolduğu Selanik Askeri Rüştiyesi, Mustafa Kemal’in meslekî hayatına olduğu kadar, fikrî hayatına da önemli katkı sağlamıştır. Bu okul disiplinli ve çok iyi bir eğitim öğretim vermekteydi. Okulun öğretmenleri de aydın fikirli ve çağını iyi kavramış öğretmenlerden oluşmaktaydı (Yalçın 2006: 41).7 Aynı zamanda Türkçe eğitime ve yabancı dile de büyük önem veren bu okul (Çam 1991: 173), dersleri ihtisas esasına göre okutan ve çoğunluğunu subayların oluşturduğu bir öğretim ve yönetim kadrosuna sahipti. Selanik Askerî Rüştiyesi’ndeki eğitim ve öğretim dönemi Mustafa Kemal’in yetişmesinde büyük rol oynamıştır. Onun ileride disiplinli bir insan olmasında askeri rüştiyelerin büyük tesiri olmuştur. Mustafa Kemal, Selanik Askeri Rüştiyesi’ni on beş yaşında 1895 yılı sonu ya da 1896 yılının Ocak ayında dördüncü olarak bitirmiştir (Yalçın 2006: 41).

Mustafa Kemal Selanik Askerî Rüştiyesi’ni bitirdikten sonra İstanbul Kuleli Askerî Lisesi’ne gitmek istemiştir. Ancak rüştiyeye mümeyyiz olarak gelen Hasan Bey, onu bu düşüncesinden vazgeçirerek, Manastır Askerî İdadisi’ne gitmesini sağlamıştır. Manastır Askerî İdadisi’ne gitmekle, hem ailesinden hem de doğup büyüdüğü şehir Selanik’ten uzak kalmıştır. Osmanlı döneminde Selanik, Kosova ile birlikte Makedonya’nın üç önemli vilayetinden biri olan Manastır, Mustafa Kemal’in eğitiminde ve fikri gelişiminde önemli rol oynamıştır (Yalçın 2006: 44).

Mustafa Kemal 1898 yılının Aralık ayında Manastır Askerî İdadisi’ndeki öğrenimini başarıyla tamamladıktan sonra (Güler 1999: 1-110), İstanbul Pangaltı’daki Harbiye Mektebi’ne kaydolmuştur (Yalçın 2006: 52). Mustafa Kemal’in Harbiye’deki arkadaşları öncelikle Manastır İdadisi’nden gelenlerdi. O, Akademide kültürel çalışmalara çok önem veriyordu (Yalçın 2006: 57, 68). Bu çalışmaları onun fikirlerinin olgunlaşmasında çok mühim rol oynamıştır. Mustafa Kemal’in meslek hayatıyla birlikte, fikirlerinin olgunlaşmasında Harbiye Mektebi’nin büyük tesiri olmuştur.

2.2. Çevresinin, Öğretmenlerinin, Okuduğu Kitapların, Düşünür ve Düşünce Akımlarının Etkileri

2.2.1. Öğretmenlerinin Rolü: Atatürk’ün kişiliğinin oluşumunda onu yetiştiren öğretmenlerin mühim bir yeri vardır. Özellikle, onun ileride yapacağı inkılâpları gerçekleştirmesinde öğretmenlerinin menfi ya da müspet tutum ve tavırları etkili olmuştur. Onun ilköğrenime başladığı Hoca Kasımpaşa semtindeki Fatma Molla Kadın Mektebi’nin hüsnühat öğretmeni Çopur Hafız Emin Efendi ile Mülkiye Rüştiyesi’nde matematik öğretmeni ve müdür yardımcısı olan ve “Kaymak Hafız” diye anılan Hüseyin Efendi’nin uygulamaları, Mustafa Kemal’i yaptığı inkılâplar sırasında kötü bir örnek olarak etkilemiş ve onu geçmişin eğitim kurumlarının ortadan kaldırılmasının gereği noktasında yönlendirmiştir. Mustafa Kemal’in Mülkiye Rüştiyesi’nden ayrılmasında Hüseyin Efendi’nin önemli etkisi olmuştur (Yalçın 2006: 39). Kendisi Harp Okulu’nda talebe iken; “Mülkiye Rüştiyesi’nden ayrılmamda bu kaba ve insafsız hareketi başlıca rol oynamıştır” (Cebesoy 1967/I: 14) demiştir.

Bu dönemde Mustafa Kemal’i olumlu yönde etkileyen ve onun bir devlet ve siyaset adamı haline gelmesinde, çok büyük katkıları olan öğretmenleri arasında Şemsi Efendi’nin mümtaz bir yeri vardır. Onun yeni eğitim yöntemi sayesinde talebelerin, bir üst düzey olan rüştiyedeki talebelerden daha bilgili yetişmesini sağlamıştır. Mustafa Kemal’in yenilikçi fikirlerinde, disiplin uygulamalarının gelişmesinde, Şemsi Efendi’nin öğretim metodunun önemli etkisi olmuştur (Yalçın 2006: 39).8

Mustafa Kemal, Selanik Askerî Rüştiyesi’nde okuduğu sıralarda zekiliği ve çalışkanlığıyla komutanlarının dikkatini çekmiştir. Mustafa Kemal Rüştiyede, matematik dersine özel alaka göstermiş, bu dersin öğretmeni Yüzbaşı Mustafa Sabri Bey, onun yetenek, yaratıcılık ve olgunluğunu tespit ederek, ona ‘Kemal’ adını vermiştir. Böylece, onun, kendisinden ve arkadaşlarından farklı ve üstün durumunu tespit etmiş, bu durum ona daha iyiye, daha güzele doğru gitmesi için devamlı bir teşvik nedeni sağlamıştır. Mustafa Kemal Atatürk’ün bir lider olarak akılcı ve hesap kitap adamı olmasında doğrudan rol oynayan bir faktör olarak matematik sevgisi kabul edilecek olursa, Yüzbaşı Mustafa Bey’in üzerindeki yönlendirici etkisi daha da önem kazanmaktadır (Yalçın 2006: 41). Bu hadise onu sürekli daha büyük başarı ve faziletler peşinde koşmaya iten bir destek vazifesi görmüştür (Akyüz 1992: 72).

Selanik Askerî Rüştiyesi’nde Mustafa Kemal’e özel ilgi gösteren öğretmenlerinden birisi de Fransızca öğretmeni Yüzbaşı Nakiyüddin Bey’dir. Mustafa Kemal, Yüzbaşı Nakiyüddin Bey’in kendisini fikren nasıl yetiştirdiğini şu şekilde ifade eder; “Bana henüz ilk bilgileri öğretirken gelecek için ilk fikirleri de vermişti.” (Atatürk’ün Söylev ve Demeçleri, 1959/II: 196-197).

Mustafa Kemal’i etkileyen öğretmenlerinden birisi de tarih öğretmeni Mustafa Tevfik Bey’dir. Onun tesiriyle Fransız Devrimi’nin temel ilkelerinden biri olan “hürriyet” kavramı ile tanışmıştır (Yalçın 2006: 49). Türk tarihini iyi bilen ve öğrencilere tarih zevkini aşılayan Tevfik Bey, Mustafa Kemal’e yeni bir ufuk açmıştır (Cebesoy 1967/I: 18). En önemlisi Mustafa Kemal’de derin tarih bilgisi ve bilincinin oluşmasında, Tevfik Bey’in çok büyük rolü olmuştur (Unat 1964: 85). Özellikle Mustafa Kemal, okul sıralarındaki derslerinden itibaren tarih okumasını sevmiş ve hayatının her devrinde muhtelif tarih kitapları ve meseleleri ile meşgul olmuştur (Afet İnan 1968: 191, 192). Onun tarih sevgisi ve tarih bilinci, Türk inkılâbının temel vasıflarından birini oluşturmuştur. Tarihe büyük ehemmiyet veren Mustafa Kemal; “Tarih bir milletin nelere müsait olduğunu ve neler başarmaya muktedir bulunduğunu gösteren en doğru bir kılavuzdur” (Aksan 1986: 115) ifadesiyle tarihin millet hayatında ne denli önemli bir unsur olduğunu ortaya koymuştur.9

Mustafa Kemal’in yetişmesinde mühim rol oynayan Manastır şehrindeki Askerî İdadi’ye gitmesini teşvik eden Hasan Bey’in etkisini de unutmamak gerekir (Cebesoy 1967/I: 17).10 Hocasının tavsiyesine uyarak Manastır Askeri İdadisi’ne giden Mustafa Kemal, burada kendini her alanda yetiştirme imkânı bulmuştur. Mustafa Kemal, ders dışında siyasî, sosyal, idarî ve iktisadî sahada araştırmalar yapmış, çevresindekilerle memleket meselelerini tartışmıştır. Bu ona, kendi fikir ve ideallerini açıklama ve ileri sürme cesareti kazanmasını sağlamıştır (Gündüz 1973: 13).

2.2.2. Okuduğu Kitaplar, Yazar ve Düşünürler ile Fikirlerin Etkisi

Mustafa Kemal’de inkılâp fikirlerinin oluşumuna tesir eden faktörler arasında, okuduğu kitaplarında önemli tesiri olmuştur. Mustafa Kemal, okumaya meraklı ve okumayı seven bir insandı. Çocukken de kitap okumaya meraklı olan Mustafa Kemal, elindeki iki kuruştan biriyle mutlaka bir kitap alırdı (Granda 1973: 267). Manastır Askerî İdadisi’nde iken kendini geliştirecek kitaplar okumaya gayret etmiştir. Burada hem okuduğu kitaplar hem de aydın fikirli ve ileri görüşlü, bilgili okul hocaları sayesinde bilgi ve görgüsünü artırmıştır. Okul yıllarında Türk tarihine çok alakadar olmuş, okuduğu kitaplar Türk tarihine dair bilincinin gelişimine katkı sağlamıştır. Tarih kitaplarının yanı sıra Avrupa’da o dönemlerde yeni ortaya çıkmış antropoloji, arkeoloji, Eski Çağ ve dil meselelerine dair kitapları okur, o alanların uzmanlarına danışır ve bilgi edinirdi (Dilaçar 1975: 475).

Mustafa Kemal, okuyacağı kitapları özenle seçer, çok dikkatli okur ve önemli gördüğü yerleri not ederdi. Din, felsefe, tarih, siyaset, sosyoloji alanlarına daha çok ilgi duymuştur (Dönmez 1998: 60-70). Toplumsal ve devrimci görüşlerinin oluşmasında büyük tesiri görülen Şehbenderzade Filibeli Ahmet Hilmi’nin Allah’ı İnkar Mümkün mü? isimli eserini okuduktan sonra kitap hakkında ki düşüncelerinden şu şekilde bahsetmiştir;

“Allah’ı inkar mümkün mü? Yapıtını bitirdim. Bütün filozofların, değişik dinlere bağlı olan doğalcılar, usçular, özdekçiler, bilginler, düşünürler, gizemciler, hepsi ruhun var olup olmadığını, ruhun ve cismin bir veya ayrı olup olmadığını, ruhun kalıcı olup olmadığını inceliyor. Bu incelemelerde bilim ve tekniğe dayananlar kabul edilebilir. İmam Gazali, İbn Rüşd gibi Müslüman imamların sözleri de genel anlayıştan tümüyle farklıdır; yalnız anlatımlarında çok simge var. Dindar düşünürler, kuramları, bilimleri, teknikleri ve felsefeyi şeriatın sözlerini yorumlamak için evirip çevirmeye çaba göstermişler” (Turan 1989: 12).

Mustafa Kemal’in Manastır Askerî İdadisi’nde okuduğu dönem, Abdülhamit yönetiminin sansür yasağının olduğu bir dönemdi. Buna rağmen yasak yayınlar bütün Balkanlarda özellikle Manastır ve Selanik’te gizliden gizliye okunuyordu. Mustafa Kemal, Manastır’da askerî öğrenciliği sırasında yasak yayınları okuma fırsatı da bulmuş, ‘istibdat’ idaresinin yasak ettiği inkılâpçı edebiyata ilgi duymuştur.

Mustafa Kemal, Osmanlı aydınlarının taşıdığı ve geliştirdiği batı fikirlerinden de etkilenmiştir. Özellikle Türk inkılâbında akılcılık, rasyonalizm ve pozitivizmin izlerini görmemiz bunun delilidir (Turan 1989: 11).11 Fransız Devrimi ile birlikte ortaya çıkan düşünce akımlarından özellikle ulusal egemenlik, milliyetçilik, laiklik gibi ilkelerden de etkilenmiştir (Mumcu 1992: 81; Eroğlu 1982: 16-22). Ancak onun inkılâp fikri tamamen çağdaş ve Türk milletinin karakterine özgü yeni bir olgudur. Örneğin Fransa’dan esinlenilen demokrasi kavramını aynen tatbik etmemiş, Türk milletinin karakteriyle bağdaştırmıştır; “Türk demokrasisi Fransa İhtilali’nin açtığı yolu takip etmiş, lakin kendisine has vasf-ı mümeyyizi (belirgin niteliği) ile inkişaf etmiştir (gelişmiştir)” (Karal 1956: 44; Mumcu 1992: 81). Mustafa Kemal, Fransız Devrimi fikirlerinden etkilendiğini 14 Temmuz 1922’de Fransız Devrimi’nin yıldönümünde yapmış olduğu bir konuşmada şu şekilde izah etmiştir:

“Başlangıçta ayaklanma ve ihtilal biçiminde görülen hareket, yerini bir inkılâba bırakır. Fransız İhtilali de bu dönemlerden geçmiş ve milletin toplumun vicdanında yerleşmiş onun için evrensel olmuştur.” “Baylar, işte bu gün 1789 Temmuzunun 14. gününü burada kutluyoruz ve bu Fransızların milli bayramı olduğu kadar henüz özgürlüklerine kavuşmamış milletlerin de sevinecekleri bir gündür....” “....Türk tarihinde de istilacı orduların İzmir’den denize dökülmesi, bizim milli tarihimiz için dünya tarihinde yepyeni bir dönem olacaktır. Bu da artık istila için hiçbir memleketin özgürlük ve bağımsızlıklarını yok etmeye olanak bulunmayışıdır. Eğer haksızlığa uğramış Asya ve Afrika milletleri, bizim bağımsızlık mücadelemizden bir ibret almışlarsa, kendileri için pahalıya da mal olsa, bu yola gideceklerdir. Özgürlük ve bağımsızlıktan yoksun bir millet için, yaşamanın ne anlam, ne de zevki vardır.” “Baylar, bizim Asya‘yı ayaklanmaya ve savaşmaya sürükleyişimiz Fransız milletini kahramanca hareketlere sürükleyen nedenlerden daha az kuvvetli ve daha az mantıkî değildir” (Tansu 1969: 560-563).

Mustafa Kemal, Fransız Devrimi düşüncesinden etkilendiğini ve ondan ilham aldığını şu cümlelerle ortaya koymuştur:

“Fransa İhtilali bütün cihana hürriyet fikrini nefheylemiştir ve bu fikrin halen esas menbaı bulunmaktadır. Fakat o tarihten beri beşeriyet ilerlemiştir. Türk demokrasisi Fransa İhtilali’nin açtığı yolu takip etmiş, lakin kendine has vasf-ı mümeyyizle inkişaf etmiştir. Zira her millet inkılâbını içtimai muhitinin tazyikat ve ihtiyacına tabi olan ve hal ve bu ihtilal ve inkılâbın zaman-ı vukuuna göre yapar” (Atatürk’ün Söylev ve Demeçleri, 1997: 120).

Fransız Devrimi’nin dünyayı nasıl ve ne şekilde etkilediğini görmüş olan Mustafa Kemal, devrimin getirdiği fikirleri çok iyi incelemiş, faydasına inandığı fikirlerden de ayrılmamıştır. Daima halkın egemenliğinden yana olmuş, millet düşüncesini her şeyin üstünde tutmuş, “milli devlet” ideali ile yaşamıştır (Tünay 1981: 163). Fransız Devrimi özellikle siyasî alanda Mustafa Kemal’in fikirlerinin gelişmesinde büyük rol oynamıştır (Karal 1980: 5, 6).

Mustafa Kemal, hem batı hem de doğu düşünürlerini okumuş, bilgi ve görgüsünü artırmıştır. Daha o dönemlerde askerlik mesleği yanında, dönemin tarih, sosyoloji ve hukuk kitaplarını da okumuş, incelemiş ve takip etmiştir. Batılı aydınların eserlerini de çok iyi okumuş ve inceleme fırsatı bulmuştur (Tünay 1981: 163). Voltaire’in akıl ve ilim düşüncesinden etkilendiği12 Rousseau’nun Du Contrat Social ve Montesquieu’nün The Spirit of Laws (Kanunların Ruhu) eserlerini okumuştur. Kendi yazarlarından ise Ziya Paşa, vatan ve özgürlük kavramlarını öğrendiği Namık Kemal, Tevfik Fikret, Mehmet Emin, Süleyman Nazif, Abdullah Cevdet, Celal Nuri, Kılıçzade Hakkı ve Şehbenderzade Hilmi’nin eserlerini okumuştur (Karal 1980: 9; Çaycı 1989: 48). Özellikle, siyasî fikirlerin tetkiki açısından okuduğu kitaplar önemli iz bırakmıştır.13 Ayrıca, Faruk Nafiz Çamlıbel, Yahya Kemal, Mehmet Emin gibi şairlerde millî duygu ve düşünceler, hissi yönden ona tesir etmişlerdir (Dönmez 1998: 60- 70). Onda millî hislerin canlanmasını sağlayan Mehmet Emin Yurdakul’un şiirlerini de burada zikretmeden geçemeyiz. Osmanlı’nın son dönemlerinde Türkçülük fikrini şiirleriyle dile getiren Mehmet Emin, Türkçülük düşüncesinin gelişmesine büyük katkı sağlamıştır. Onun 1899’da Türkçe şiirlerinde kaleme aldığı; “Ben bir Türküm, dinim, cinsim uludur / Sinem, özüm ateş ile doludur / İnsan olan vatanının kuludur / Türk evlâdı evde durmaz, giderim” dizeleri, Mustafa Kemal üzerinde büyük tesir uyandırmıştır.14

Mustafa Kemal, batılılaşmada batıcı aydınların fikir ve düşüncelerinden istifade etmiştir. Ancak onların batıcı fikirlerini aynen tatbik etmemiş, kendine has, Türk milletine özgü bir batılılaşmadan yana olmuştur;

“… Tetkikat ve tetebbuatımıza zemin olarak alelekser kendi memleketimizi, kendi ananelerimizi, kendi hususiyetlerimizi ve ihtiyaçlarımızı almalıyız… Bir millet için saadet olan bir şey diğer milletler için felaket olabilir. Aynı sebep ve şerait birini mesut ettiği halde, diğerini bedbaht edebilir. Onun için bu millete gideceği yolu gösterirken, dünyanın her türlü ilminden, keşfiyatından, terakkiyatından istifade edelim, lakin unutmayalım ki, asıl temeli kendi içimizden çıkarmak mecburiyetindeyiz. Milletimizin tarihini, ruhunu, ananatını, sahih, salim, dürüst bir nazarla görmeliyiz…” (Atatürk’ün Söylev ve Demeçleri, 1989: 144-145).

Mustafa Kemal’in fikirlerinin gelişmesinde Meşrutiyet döneminin fikri birikiminin büyük rolü olmuştur. Mustafa Kemal, Meşrutiyet döneminde İttihat ve Terakki’nin siyasî, sosyal ve kültürel politikalarını çok iyi etüt etmiş, hayalciliğin ve her türlü hayal perestliğin bir memleketi ve milleti nasıl felakete sürüklediğini görmüş, bu onu gerçekçi bir lider konumuna getirmiştir (Baycan 1998: 63; Banoğlu 1981: 496; Paruşey 1973: 351).15

2.2.3. Arkadaşları ve Çevresinin Rolü

Gerek Manastır gerekse Harbiye’de tanıştığı farklı fikir ve idealde olan arkadaşlarıyla sohbet etmesi, fikirlerinin gelişmesinde önemli rol oynamıştır. Manastır’da sınıf arkadaşları sadece Selanik Rüştiyesi’ndekiler değildi. Manastır bölgesine bağlı olan, Üsküp, İpek, İşkodra, Yanya ve Manastır Askerî Rüştiyelerinden gelen gençler de vardı. Burada farklı karakter, mizaç ve seviyede gençlerle tanışmış, bu farklılıklar Mustafa Kemal’in fikir hayatına zenginlik katmıştır.16

Manastır Askerî Rüştiyesi’nde Mustafa Kemal, farklı fikir ve ideallerde öğrencilerle karşılaşmış ve gerek öğretmenlerinden gerekse okul arkadaşlarından yararlı fikirler edinmiştir. Mustafa Kemal, faydasına inandığı her fikre açık olmuştur. Hiçbir fikre ön yargılı olmadığından, okul yıllarında her fikir ve idealden birçok arkadaşı olmuştur. Onlarla yaptığı sohbetlerde fikir teaddisinde bulunmuştur.

Harbiye Mektebi, Mustafa Kemal’in meslekî eğitiminde olduğu kadar sosyal, siyasî, idarî, fikrî ve iktisadî meselelerde de kendisini yetiştirme imkânı bulmasını sağlamıştır. Burada sonradan İttihat ve Terakki’nin hatibi olacak olan ve genç yaşta Birinci Dünya Harbi sırasında hayatını kaybeden ve Bursa İdadisi’nden kovularak Manastır İdadisi’ne yollanan Ömer Naci, edebiyat ve şiir hususunda Mustafa Kemal’i en çok etkileyen arkadaşlarından biriydi.17 Ömer Naci, Mustafa Kemal’in hatıralarında özel yer verdiği kişiler arasındadır (Tezer 1995: 209-210; krş. Kılıç Ali 1955: 20-21). Mustafa Kemal’e şiiri ve edebiyatı sevdiren Tevfik Fikret’i, Mehmet Emin’i tanıtan Ömer Naci olmuştur (Cebesoy 1967/I: 18). Ömer Naci’nin, Mustafa Kemal’in fikri alt yapısının oluşmasında diğer faktörlerle birlikte önemli bir rol oynadığı kesindir (Yalçın 2006: 48-49).

Mustafa Kemal’in yakın çevresindeki arkadaşlarına 1902’de Harp Akademisi’nin birinci sınıfında iken, batılı anlamda bir idareden bahsettiğini Ali Fuat (Cebesoy) nakleder (Cebesoy 1981: 9). Öğrencilik yıllarında çeşitli yerlere gider ve oralarda fikirlerini açıklama imkânı bulurdu. “İstibdat” idaresinin olduğu bir dönemde Mustafa Kemal, fikirlerini ve ideallerini cesaretle etrafındakilerle paylaşmıştır. Bir gün Harbiye’de iken Ali Fuat (Cebesoy)’un babası İsmail Fazıl Paşa’nın Kuzguncuk’taki köşkünde misafir edilir. O gece orada kalır ve ertesi gün (27 Haziran Cuma) köşke gelen eski Berlin Elçisi ve Bayındırlık Bakanı Osman Nizami Paşa ile tanışır. O sırada Harp Akademisi’nin birinci sınıfında bulunan Mustafa Kemal, Osman Nizami Paşa ile Osmanlı devletinin geleceği üzerinde konuşurken, ilk defa inkılâp düşüncesinden bahsederek, yeni bir idarî teşekkülün zarureti üzerinde durmuştur (Eroğlu 1998: 25). Osman Nizami Paşa’nın; “İstibdat idaresi bir gün elbette yıkılacaktır. Fakat onun yerine batılı manada bir idare gelip de memleketi her bakımdan acaba kalkındırabilecek midir? Ben buna inanmıyorum” demesi üzerine Mustafa Kemal;

“Paşa Hazretleri, batılı manadaki idareler de zamanla gelişmişlerdir. Bugün uyur gibi görünen milletimizin çok kabiliyetli cevherleri vardır. Fakat bir inkılâbın meydana gelmesinde bugün iş başında olanlar, yerlerini muhafaza etmeye kalkarlarsa, o vakit buyurduğunuzu kabul etmek gerekir. Yeni nesiller içerisinde her konuda güvenilir insanlar çıkacaktır” der.

Bunun üzerine Osman Nizami Paşa;

“Mustafa Kemal Efendi oğlum, sen, bizler gibi yalnız erkân-ı harp zabiti olarak normal bir hayata atılamayacaksın. Keskin zekân ve yüksek kabiliyetin memleketin geleceği üzerinde müessir olacaktır. Bu sözlerimi bir kompliman olarak alma. Sende, memleketin başına gelen büyük adamların daha gençliklerinde gösterdikleri müstesna kabiliyet ve zekâ emareleri görmekteyim. İnşallah yanılmamış olurum” (Cebesoy 1967/I: 36).

diyerek Mustafa Kemal’den övgüyle söz eder. Mustafa Kemal’in konakta Nizami Paşa’ya batılı manada bir idareden bahsetmesi, saltanatın da ötesinde bir idarenin varlığını ortaya koymaktadır (Tünay 1981: 161).

Harbiye Mektebi’nde okuduğu sıralarda, Ahmet Emin Yalman, onun inkılâba dair fikir ve idealini Vakit gazetesinde Türkiye Büyük Millet Meclisi Reisi Gazi Mustafa Kemal Paşa Hazretlerinin Tarihçe-i Hayatı adıyla yayınlanan yazısında açık bir şekilde anlatır;

“Harbiye senelerinde siyaset fikirleri baş gösterdi. Vaziyet hakkında henüz nafiz bir nazar hâsıl edemiyorduk. Sultan Hamid devri idi. Namık Kemal Bey’in kitaplarını okuyorduk. Takibât sıkı idi. Ekseriyetle ancak koğuşta, yattıktan sonra okumak imkânını buluyorduk. Bu gibi vatanperverâne eserleri okuyanlara karşı takibat yapılması işlerin içinde bir berbatlık bulunduğunu ihsâs ediyordu. Fakat bunun mahiyeti gözlerimiz önünde tamamıyla tebellür etmiyordu. Erkânıharp sınıflarına geçtik. Bende ve bazı arkadaşlarda yeni fikirler peyda oldu. Memleketin idaresinde ve siyasetinde fenalıklar olduğunu keşfetmeye başladık” (Yalman 1338: 1).

2.3. Meslek Hayatının Rolü

Ali Fuat Cebesoy’un anlatımıyla Mustafa Kemal, 1905’te topçu stajı için Şam’a gitmeden önce Beyrut’ta yakın çevresine “Dava yıkılmak üzere olan imparatorluktan, önce bir Türk devleti çıkarmaktır” (Cebesoy 1967/I: 108) der. Mustafa Kemal, yeni bir davanın, bir Türk devleti davasının varlığını daha 1905 yıllarında ortaya koymuştur. Mustafa Kemal’in bu düşüncesi, onun inkılâp, değişim, fikir ve idealine çok önceden sahip olduğunun bir göstergesidir.

11 Ocak 1905’te Erkan-ı Harbiye Mektebi’ni Erkan-ı Harbiye Yüzbaşısı olarak bitirdiğinde, dönemin yeni siyasî fikirlerine vakıf olmuş olan Mustafa Kemal, Ekim 1905’te Müfit ve Lütfi Beylerle tıbbiyenin son sınıfında iken, hürriyetçi fikirlerinden dolayı okuldan uzaklaştırılıp Şam’a sürgün edilen Mustafa (Cantekin) Bey’in buradaki evinde, hürriyet ve vatan meselesi tartışmaları sırasında, “Vatan ve Hürriyet Cemiyeti”ni teşekkül etmişlerdir (Genç Osman, Banoğlu 1971/I: 102).

Münir Hayri Egeli, Mustafa Kemal’in cumhuriyet ve inkılâp düşüncesini 1906’da Suriye’de arkadaşı Halil Bey’le yaptığı bir konuşmada dile getirdiğini yazmaktadır (Egeli 1954). Mustafa Kemal, Harbiye Mektebi’ni bitirip görev aldığı bu dönemde Şam’da yakın çevresine siyasî fikirlerinden bahsetmiştir. Bu dönem onun aynı zamanda siyasî fikirlerinin de belirmeye başladığı bir dönemdir. Mustafa Kemal, Suriye’de özellikle millet hakimiyetine dayalı bir devlet kurulması için yakın arkadaşlarından iş birliği istemekte idi (Egeli 1954: 34-35).18 Bu durum onun millet hâkimiyetine dayalı yeni bir devlet ihdas etme düşüncesini fikrî şekilden fiili bir zemine taşıma hareketi içinde olduğunun da göstergesidir. Mustafa Kemal, inkılâp fikirlerini, buna bağlı olarak da millet hâkimiyetine dayalı yeni bir rejim kurma düşüncesini, gittiği her yerde yakın arkadaşlarıyla paylaşması, ileride millî hâkimiyete bağlı kurmayı tasarladığı yeni rejime taraftar bulmayı hedeflediğini göstermektedir. Özellikle bir ordu mensubunun saltanat ve hilafet odaklı bir memlekette millî hâkimiyetten söz etmesi takdire şayan bir harekettir. Mustafa Kemal, Şam’dan sonra gittiği Beyrut’ta da millî hâkimiyete dayalı bir devlet kurma düşüncesini belirtmekteydi (Cebesoy 1967/I: 108). Şam’da bulunduğu sıralarda da cumhuriyet fikrini samimi arkadaşları ile paylaşmıştır. Nitekim, o, Şam’da saltanata bağlılık şenlikleri düzenlenirken, yakın arkadaşı Halil Bey’le bu şenliklerin gereksizliği üzerine konuşurken, o, padişah düşüncesine saplanılmamasını, cumhuriyetin kurulabileceğini belirtmiştir (Egeli 1954: 34-35).

Nisan 1906 tarihinde, Selanik’te gizli olarak Vatan ve Hürriyet Cemiyeti’nin ilk şubesini açtığında, orada yakın dostlarıyla vatanı ve memleketi içine düştüğü buhranlardan kurtarmak için yapılması elzem olan şeyler hakkında mütalaalar yapmakta idi.19 Mustafa Kemal ve arkadaşları hususiyetle, “istibdada” karşı ihtilalci bir harekete taraftardılar. “İstibdat” yönetiminin ancak bir ihtilal ile ortadan kalkabileceğini ifade etmiştir (Cebesoy 1967/I: 96; Kızıldoğan 1937/I: 622).20

Selanik’te, askerî bir kulüpte verilen bir konferanstan etkilenen Mustafa Kemal, yanında bulunan arkadaşlarına İkinci Meşrutiyet döneminde Meşrutiyet dönemi inkılâpları için şu değerlendirmede bulunur;

“İnkılâbı, ikmal etmek lazımdır. Biz bunu yapabiliriz. Ben bunu yapacağım. Evet, inkılâp yapacağız. Bugüne kadar yapılan inkılâp kâfi sayılmaz. Fazlasını yapacağız. Devlet hizmetleri veren arkadaşları Mustafa Kemal’e; ‘Bütün bu işlerin içinde sen ne olacaksın?’diye sorduklarında onlara şu cevabı vermiştir: Ben de bu sözleri o makamlara koyabilen olacağım” (İnan 1968: 75; Eroğlu 1982: 16-22).

II. Meşrutiyet dönemi inkılâplarının yeterli gelmeyeceğinin farkında olan Mustafa Kemal, yeni ve şümullü bir inkılâp ortaya koymanın gereğini vurgular.

1907’de daha genç bir subayken, vatanın gelecekteki sınırlarını çizmiş olan Mustafa Kemal, geleceğe dönük radikal tasarılarını ise şu şekilde belirtmiştir; “Kadın ve erkek arasındaki farkları silecek yeni bir sosyal düzen kurmalıyız. Batı medeniyetine girmemize engel olan yazıyı atarak, Latin kökünden bir alfabe seçmeli, kılık kıyafetimize kadar her şeyimizle batılılara uymalıyız. Emin olunuz ki, bunların hepsi bir gün olacaktır.”21

Selanik’te Türkolog Malikof’a, ileride yapmayı tasarladığı fikir ve ideallerinden ise şu şekilde bahsetmiştir;

“Sultanlık kaldırılmalıdır, devletin yapısı mütecanis bir temele dayandırılmalıdır. Din ile devlet birbirinden ayrılmalıdır. Doğu medeniyetinden ayrılıp batı medeniyetine yönelmek zorundayız. Erkekle kadın arasındaki farkı kaldırmalıyız. Böylece yeni bir toplum düzeni kurmalıyız. Batı uygarlığına girmemizi zorlaştıran yazıyı kaldırmalıyız. Latin alfabesini kabul etmeliyiz. Kıyafetimize kadar her noktada batıya yönelmeliyiz” (Irmak 1987/III: 248).22

Görüldüğü üzere daha 1907 yıllarında, Mustafa Kemal’in ortaya koyduğu görüşler çağına göre hayli ileriydi. O dönemde bu tür fikirler basın hayatında tartışılıyor olmasına karşın şekli olarak onun dile getirmesi, o dönemlerde kararlı bir inkılâp düşüncesine sahip olduğunu göstermektedir. O, memleketin kurtulması için ortaya koyduğu fikir ve ideallerin mutlak surette hayata geçirilmesi gerektiğine inanmaktadır.

Mustafa Kemal’in yakın arkadaşlarından Falih Rıfkı, Mustafa Kemal’in yeni Türk devletini kurma düşüncesinin çok önceden beri var olduğunu belirtmektedir;

“Mustafa Kemal acı ve sert tenkitçi olduğu kadar açık sözlü idi. Daha o zaman, 1907’de, arkadaşlarına şu fikrini söylemekten çekinmemiştir: Köhneleşen ve hayatlılığını kaybeden Osmanlı İmparatorluğu gövdesi üzerine devlet oturtulamaz. Ancak Türk çoğunluğu toprağı üzerine oturtulabilir. Büyük devletlere bir likidasyon yaptırmaktansa, ihtilal idaresi bunu kendi yapmalıdır” (Atay 1998: 47-48).

Mustafa Kemal’in ileri görüşlü kişiliğe sahip olması birtakım siyasî gelişmelerin nasıl ve ne şekilde gelişebileceğini önceden sezdirtmiştir. İttihat ve Terakki Cemiyeti’nin bir siyasî parti haline gelerek, hükümeti, meşrutiyetin ilanından sonra ele alması gerektiğini, hatta Cemiyetin bu görev için programını hazırlamış olmasını, aksi takdirde İkinci Meşrutiyet’in de Birinci Meşrutiyet gibi akıbete uğrayabileceğini, İkinci Meşrutiyet’in ilanı esnasında ifade etmiştir (Cebesoy 1967/I: 114). İkinci Meşrutiyet’te eksik kalan Türk inkılabının tamamlanacağını kurmay yüzbaşı iken söyleyen Mustafa Kemal, hayatı boyunca bu inkılâpları tamamlamayı ilke edinmiştir (İnan 1954: 432- 433). Mustafa Kemal, inkılâplara yürekten inanan bir dava adamı idi. 31 Mart Olayından sonra, 1909’da Selanik’te, Beyazkule karşısındaki askerî kulüpte verilen bir konferansın ardından, Nuri (Conker), Fethi (Okyar), Kazım (Özalp) ve güvendiği diğer arkadaşlarına inkılâbı tamamlamalarını ve bunu gerçekleştirmeye muktedir olduklarını ve kendisinin de bunu yapacağını ifade ettikten sonra, yapmayı tasarladığı inkılâpları yanında bulunanlara anlatır.23 Ancak Mustafa Kemal’in daha o tarihlerde gelecek ile ilgili düşüncelerini etrafındakiler bir hayal olarak görmekte idiler.

Mustafa Kemal Sofya’ya ateşemiliter olarak görevlendirildiği sırada, İstanbul’da, “Türkiye için en uygun idare şekli cumhuriyettir” (Özalp 1963: 5) demiştir. Sofya Ateşeliğinde iken, Madam Hilda Chirstianus’un evinin bir odasında pansiyoner olarak kalıyordu. Edib Erenler, Madam Hilda’nın kendisine, Mustafa Kemal’in Osmanlı devletinin içinde bulunduğu buhranlardan ve bu buhranların ortadan kaldırılması için yapılması gerekli olan şeylerin neler olduğundan bahsetmiş ve eline fırsat geçtiği takdirde bu durumu düzelteceğini ifade ettiğini belirtmiştir.24 Mustafa Kemal, yenilikler yapmaya kesin karar vermiş, bu kararlarını gizli tutmuş ancak güvendiği kimselere fikirlerini açıklamıştır. O, cumhuriyet fikri ve devrimlerini hiçbir şekilde açığa vurmamış, salt vatanın kurtuluşu için saltanat ve hilafete dair menfi bir beyanatta bulunmamış, hatta saltanatın masuniyetinin teminine çalışılmasının gerekliliği dahi vurgulamıştır.25 Aynı zamanda Türkiye Büyük Millet Meclisi’nde hilafeti desteklemiş ve ona bağlılık sözü dahi vermiştir.26

Şükrü Tezer, Mustafa Kemal’in Birinci Dünya Harbi esnasında, devlet rejimi değişikliği üzerine Topal İsmail Paşa ile yaptığı görüşmede ileride cumhuriyetin teşekkül edileceğini, fakat şartların o an için elverişli olmadığını ifade etmiştir (Tezer 1999).

Mustafa Kemal, Ali Fuat Paşa ile birlikte Mondros Mütarekesi akabinde İstanbul’a geldikleri vakit (Bayur 1962/I: 188), ülkenin genel durumu hakkında bir değerlendirme de bulunur. Ali Fuat Paşa’ya 1907’de Meşrutiyet’ten evvel Selanik’te İttihat ve Terakki Cemiyeti’nin gizli umumî merkezinde kendisinin Misak-ı Millî’ye dair düşüncelerini izah ederken bu düşüncesini kaale almayanların, şimdiki felaketi gördüklerinde Misak-ı Millî’nin bir mesele olarak telakkisinin zaruriyetine artık kani olduklarını söyler. Fuat Paşa’ya bu sözleri söyledikten sonra, Misak-ı Millî’nin Türk devletini demokratik bir cumhuriyete götürecek bir temel olduğunu da belirtir (Cebesoy 1963: 388).

Mustafa Kemal, inkılâplarındaki teorik ve pratik tatbikin belirleyiciliğinde sürekli değişimin planlı ve programlı bir stratejisinin etkisini, 1918’de Karlsberg’de hasta yatağında yazdığı günlüğünde şu şekilde ifade etmiştir;

“Tutuculuk mu? Asla sürekli değişim zorunluluğunda olan evrende bir şeyi korumak nasıl olur? Konservatörler o adamlar ki nehrin suyunu ellerinde tutmak isterler. Onların parmaklarında bir parça çamurdan başka şey kalmaz. Tutucu değilim, çünkü eskimiş ve kırılmış bir âlemi muhafaza edemem...” (Ergin 1977: 9).

Mustafa Kemal, hayatı boyunca uyguladığı ve devrimin başlıca ilkeleri arasına giren kararlılık sayesinde inkılâplar gerçekleşmiştir. 6 Temmuz 1918 tarihinde hatıra defterine ise şunları yazmıştır; “Benim elime büyük bir salâhiyet ve kudret geçerse ben sosyal hayatımızda arzu edilen inkılâbı bir anda bir darbe ile uygulayabileceğimi zannederim” (Kuruç 1987: 18-19).

Mustafa Kemal ileride yapmayı planladığı ve bir sır olarak sakladığı devrimleri, Erzurum Kongresi esnasında (7/8 Ağustos 1919) Mazhar Müfit Kansu’ya aktarmıştır (Kansu 1986/I: 130-131). Daha o dönemlerde, cumhuriyet, tesettür, fes, saltanat, Latin harflerine dair inkılâpları İstiklal Savaşı’nda tasarlamıştır (Palazoğlu 1990: 5). Mazhar Müfit’in; “Muvaffakiyet ve zafere ulaştığımız takdirde hükümet şekli ne olacak? Bu hususta sarih bir şey söylemediniz” şeklindeki sualine Atatürk şu cevabı vermiştir:

“Azizim Mazhar Müfit Bey, bu mesele hakkında şimdiden bir şey söylemek istemem. Hatta mevzubahis etmemek doğru olur. Bu bahsi münakaşa etmenin zamanı gelmemiştir. Gelince görüşürüz. Karar verilen her şeyin tatbiki için vakit ve zamanı beklemek ve o zamanın geldiğini bilmek lâzımdır. Şimdi sadece düşman tazyiki altında bulunan padişahı ve muhasım kuvvetlerin işgal ve istilâsına uğramış olan vatanımızı kurtarmak için çalıştığımızı ifade etmekte fayda vardır. Bugünün ve içinde bulunduğumuz şartların icabı budur” (Kansu 1986/I: 30).

7/8 Temmuz gecesi sabaha karşı Mustafa Kemal, Mazhar Müfit ve Süreyya Beylerle yaptığı görüşmede, konuşmaya başlamadan önce bir şart ileri sürer; “Defterin bu yaprağı kimseye gösterilmeyecek; görüşme, sonuna kadar mahrem kalacak, bir ben, bir Süreyya, bir de sen bileceksin. Şartım budur” der ve devam eder;

“Zaferden sonra şekli hükümet cumhuriyet olacaktır. Buna size daha önce de bir sualiniz nedeniyle söylemiştim. Bu bir. İki; padişah ve hanedan için zamanı gelince gereken işlem yapılacaktır. Üç; tesettür kalkacaktır. Dört; fes kalkacak, medeni milletler gibi şapka giyilecektir. Bu anda kalemi elinden düşüren Mazhar Müfit Kansu, Mustafa Kemal’e bakarak: “Darılma ama Paşam sizin de hayalperest tarafınız var” der. Mustafa Kemal: “Bunu zaman belirler” diye cevaplandırır. Sen yaz der; Beş; Latin harfleri kabul edilecek.” Mazhar Müfit Kansu;” Paşam kafi, kafi, cumhuriyet ilanını muvaffak olalım da üst tarafı yeter” diyerek yanlarından ayrılır (Kansu 1986/I: 131-132).

Misak-ı Millî27, Alî Fuat Cebesoy’a göre, Mustafa Kemal’in 1920’lerde İstiklal Savaşı’mızın esas maksadını özetleyen bir program olmakla birlikte, daha 1907’de vatanın içinde bulunduğu siyasî, iktisadî ve idarî buhranlardan kurtarmak için planladığı çok yönlü bir idealdir.28 Cebesoy, Misak-ı Millî’yi Atatürk inkılâplarının temeli olarak da görür (Cebesoy 1967/I: 53).

3. Sonuç

Sosyal olguların başlangıcı ve gelişiminin bir süreci vardır. Hiçbir olay bir anda aniden meydana gelmez. Tarihi hadiseleri birtakım siyasî ve sosyal gelişmeler meydana getirir. Her sosyal olguda olduğu gibi Mustafa Kemal’de inkılâp fikri ve ideali çok önceden var olan bir durumdur, yani inkılâp düşüncesi kendisinde daha önceden var olan bir gerçekliktir. Mustafa Kemal inkılâplarının seyrine ve muhtevasına baktığımızda, bu yenilik ve değişimlerin bir anda tasarlanan bir olgu olmadığı hükmüne varırız.

Mustafa Kemal’deki inkılâp fikirlerinin oluşumunda sosyal, siyasî, iktisadî ve kültürel gelişme ve birikimler olduğu kadar, onun doğuştan getirdiği hususiyetlerin de büyük önemi vardır. Onun zeki, anlama kabiliyeti, çabuk kavrama becerisi, dış çevreden aldığı edinimleri geliştirmiş ve şekillendirmiştir. Ondaki inkılâp fikirleri okul sıralarına kadar götürülebilir. Bunun yanı sıra; çevresi, çocukluk ve gençlik dönemleri, eğitimi, arkadaşları, öğretmenleri, okuduğu kitaplar ile fikir hayatı ondaki inkılâp fikirlerinin ortaya çıkmasına ve gelişmesine yol açmıştır.

Harbiye Mektebi’nde okurken edindiği hürriyet fikirlerini Beyrut’ta, Şam’da, Selanik’te güvendiği arkadaşlarına anlatmış, ondaki hürriyet fikri giderek ileride gerçekleşecek devrim programına dönüşmüştür.

Mustafa Kemal’in, Türk inkılâbının başından itibaren sistemli ve planlı hareketle bir düşünce bütününe ulaşmasını, ancak onun daha önceden bilgi birikimi ve deneyimine sahip olmasıyla izah edebiliriz (Mumcu 1992: 81). Osmanlı’nın son zamanlarında yaşanan siyasî, idarî, iktisadî, toplumsal ve fikrî gelişmeler Mustafa Kemal için bir laboratuar vazifesi görmüştür. Osmanlı devletinde özellikle İkinci Meşrutiyet döneminde yapılmaya çalışılan yenileşme hareketleri ile bu uzun tarihi süreç, Mustafa Kemal’in bilgi ve deneyiminin artmasında ve hazırlanmasında önemli rol oynamıştır (İnalcık 1998: 125-132; Karal 1988/8: 482-568).

Mustafa Kemal’in fikir dünyasının gelişmesine ve olgunlaşmasına tesir eden faktörler, millî bir devletin kurulmasına, çağdaş toplumun ve devletin ortaya çıkmasına yol açmıştır (Yavuz 1997: 449-451).

1 Selanik için bkz. İslam Ansiklopedisi (1980), “Selanik” maddesi, c. X, İstanbul: MEB.
2 Mustafa Kemal, okul yıllarına dair bu hatırasını 1922 tarihinde şu şekilde izah etmiştir; “Çocukluğuma dair ilk hatırladığım şey, mektebe girmek meselesine aittir. Bundan dolayı annemle babam arasında şiddetli bir mücadele vardı. Annem, ilahilerle mektebe başlamamı ve mahalle mektebine girmemi istiyordu. Rüsumatta memur olan babam, o zaman yeni açılan Şemsi Efendi’nin mektebine devam etmeme ve yeni usul üzerine okumama taraftardı. Nihayet babam işi mahirane bir surette halletti. Evvela merasim-i mutade ile mahalle mektebine başladım. Bu suretle annemin gönlü yapılmış oldu. Birkaç gün sonra da mahalle mektebinden çıktım. Şemsi Efendi’nin mektebine kaydedildim.” (Yalman 1922).
3 Mustafa Kemal’in Fatma Molla Kadın Mektebi’nde yaşadığı bu olayı Enver Behnan Şapolyo kaynak göstermeden şu şekilde bahsetmektedir; “Hafız Emin Efendi bütün çocukları yere oturtarak dizlerinde yazı yazdırıyordu. Mustafa (Kemal) buna bir türlü tahammül edemiyordu. Bir gün birdenbire ayağa kalktı. Hocası Çopur Emin Efendi: –Niçin otur muyorsun? –Dizlerim Ağrıyor! –Sana otur diyorum deyince… küçük Mustafa’nın yüzü kıpkırmızı olarak: –Oturmayacağım diye bağırdı. Hocasının: –Bana isyan mı ediyorsun? Demesi üzerine Mustafa Kemal: –Evet isyan ediyorum. Der demez, bütün çocuklar da hep bir ağızdan, –Biz de isyan ediyoruz diye bağırdılar. Hoca bu hareket karşısında kabahatini anlayarak meseleyi kapattı.” (Şapolyo 1967: 22; krş. Aydemir 1993/I: 46). Kız kardeşi Makbule Atadan hatıralarında, onun bu okulda sadece bir buçuk ay kaldığını, memnun olmadığından dolayı da babasının teşebbüsü ile oradan alındığından bahseder. Bkz. (Coşar 1973/I: 90).
4 Şemsi Efendi Mektebi için bkz. (Mert 1991/7).
5 “Yaratıcılığın var olmasında en büyük etken çocukluk çağındaki çalışmalardır. Eğer çocuk daha küçük yaşta iken yaratıcı bir çevre içinde yaşar, kendine göre oynama, deneme, yaratma olurlukları bulursa, onda yaratıcılık doğar, zamanla da gelişir. Sonunda da sosyal randımanlar verir. Bence bu yaratıcılık bir kalıt şekli olmayıp kişideki dirim enerjisinin sosyal bir randıman şeklinde oluşmasıdır. İşte Atatürk’ün çocukluk hayatında böyle bir yapıcılık, yaratıcılık devri olduğunu öğreniyoruz. Mustafa’nın çocukluk, ilk gençlik hayatında ellerle yapılan işleri ne kadar çok merak ettiğini gördük... Atatürk’ün çocukluğunda, gençliğinde ele aldığı işler hep faydalı işler, sosyal randıman verici işlerdir, kafa işleri, gönül işleridir. Marangozluk, çiçekçilik, hayvancılık hep böyledir. Sosyal kişiliğin var olmasına yarayan işler işte bu gibi işlerdir” (Baltacıoğlu 1913: 12).
6 O dönemde Balkanlardaki çocukların millî duygularla yetişmelerine tesir eden etkenler için Şevket Süreyya Aydemir’in Suyu Arayan Adam adlı eserine bakılabilir.
7 Selanik Askerî Rüştiyesi’nin öğretim kadrosu için Selanik Vilayet Salnamesi’ne bakılabilir. Selanik Vilayet Salnamesi, 1312, s. 124. Mustafa Kemal’in Selanik Askeri Rüştiyesi ile eğitim ve öğretime dair malumat için bkz. Ali Güler-Suat Akgül (1999), Atatürk ve Eğitim, Ankara: Kara Harp Okulu Basımevi.
8 Örneğin, Atatürk’ün harf inkılâbı sırasında takip etmiş olduğu yöntemler ve verdiği mesajlar, Şemsi Efendi’nin ilkokulda kendilerine alfabe öğretirken kullandığı heceleme ve okuma yöntemindeki yenilikleri hatırlatmaktadır.
9 Mustafa Kemal’in şu sözleri tarihin, özellikle millî tarihin önemine vurgu yapmaktadır; “Biz şimdiye kadar hakikî, ilmî, müspet manasıyla millî bir devir yaşamadık. Binaenaleyh millî bir tarihe malik olamadık. Bu noktayı biraz izah edebilmiş olmak için hep beraber Osmanlı tarihini hatırlayalım. Osmanlı tarihinde bütün gayretler, bütün mesai milletin arzusu, emelleri ve gerçek ihtiyaçları nokta-i nazarından değil, belki şunun bunun hususî emellerini, ihtiraslarını tatmin nokta-i nazarından vuku bulmuştur” (Baydar 1973: 18).
10 Hasan Bey, Mustafa Kemal’e; “Bundan vazgeçiniz oğlum. Manastır’a gidiniz, orada daha iyi yetişirsiniz” demiştir (Cebesoy 1967/I: 17).
11 “Benim manevi mirasım bilim ve akıldır. Zaman hızla dönüyor. Böyle bir dünyada asla değişmeyecek yargılar getirdiğini ileri sürmek usun ve bilimin gelişmesini yadsımak olur” (Kongar 1999: 41).
12 Voltaire; “ilmin ilerlemesi sayesinde insan uyanacak ve dinin değil, ilmin sesine kulak verecektir” (Dönmez 1998: 48-56).
13 Mustafa Kemal’in etkilendiği yazarlar hakkında daha fazla bilgi için bkz. (Turan 2004: 382).
14 Mustafa Kemal, Mehmet Emin’in Türklüğü yücelten bu dizelerinin kendisinde ne şekilde yer ettiğini şu şekilde ortaya koyar; “Şair Mehmet Emin Yurdakul’un ilk defa Manastır Askerî İdadisi’nde öğrenciyken okuduğum “Ben bir Tüküm, dinim, cinsim uludur” mısra ile başlayan manzumesinde, bana millî benliğimin gururunu tattıran ilk anlatımı bulmuştum. Fakat ben asıl bunu, orduya katıldığım ilk günlerde, bir Anadolu çocuğunun gözyaşlarında gördüm ve kuvveti duydum. Ondan sonra Türklük, benim en derin güven kaynağım, en engin övünç kaynağım oldu.” (Faik Reşit Unat, “Ne Mutlu Türküm Diyene”, Türk Dili Dergisi, Sayı 146, s. 77).
15 “Ben sevgili arkadaşımın düşüncelerini daha Karaferiyedeyken dinledim: Meşrutiyetin ilânı yeter çare olamaz. Cemiyetin bir siyasî parti haline gelerek hükûmeti, meşrutiyetin ilânından sonra ele alması gerekir. Parti, önceden bu görevini hazırlamış ve ne yapacağını programlaştırmış olmalıdır. Aksi takdirde, İkinci Meşrutiyet de birincisinin sonucuna uğrar” (Cebesoy 1967/I: 135-138).
16 Mustafa Kemal’in Harbiye’deki arkadaşları arasında Manastır İdadisi’nden gelenler de vardı. Ahmet Tevfik, Mustafa Nuri (Conker), Lütfi Müfit (Özdeş), Ali Fuat (Cebesoy), Arif (Ayıcı), Hayri (Tırnovacık), Kazım (Karabekir), Ömer Naci, İsmail Hakkı (Pars), Kazım (İnanç), Kazım (Özalp), Ali Fethi (Okyar) onun en samimi arkadaşları arasındaydılar.
17 Mustafa Kemal hatıralarında Ömer Naci hakkında şunları anlatır; “O zamana kadar edebiyatla çok temasım yoktu. Merhum Ömer Naci, Bursa İdadisi’nden kovulmuş, bizim sınıfa gelmişti. Daha o zaman şairdi. Benden okuyacak kitap istedi. Bütün kitaplarımı gösterdim. Hiçbirini beğenmedi. Bir arkadaşın, kitaplarımdan hiçbirini beğenmemesi gücüme gitti. Şiir ve edebiyat olduğuna o zaman muttali oldum. Ona çalışmaya başladım. Şiir bana cazip göründü. Fakat kitabet hocası diye yeni gelen bir zat beni şiirle iştigalden men etti. ‘Bu tarz iştigal seni askerlikten uzaklaştırır’ dedi. Ne var ki, güzel yazmak hevesi bende baki kaldı” (Cebesoy 1967).
18 Bu hususu Mazhar Müfid Kansu şu şekilde belirtir; “Ya culûs-u hümayun veya velâdet-i hümayun şenlikleri yapılıyordu. Mustafa Kemal ile beraber donanmayı seyretmeye çıkmıştık. Birden kolumu tuttu: “–Halîl, dedi, “bir adam için böyle donanma yapmak budalalık değil mi?” Zaten mimli olduğumuz için gayr-i ihtiyarî etrafıma baktım. O hiç aldırmadan devam etti:”–Bir millet kendi kurtuluşu için şenlik yapabilir. Nihayet kendisine pek büyük hizmetler etmiş olan bir adam için de şenlik yapabilir diyelim. Fakat hanedan-ı Âli Osmân içinde kazara bazıları bu memlekete hizmet etti diye onun nesline neden donanma yapılsın. Padişah dünyaya gelmekle memlekete hayırlar mı geldi?” Ben, bu kadar sıkı altında etrafımızda zaptiyeler dolaşırken, bu kadar cesur konuşmaktan ürkmüştüm. Fakat Mustafa Kemal devam etti:”– Padişah da kim oluyormuş. Padişahlık ne demekmiş.” Ben: “–Peki memleketi nasıl idare edeceğiz? Sultan Hamid fenadır seninle beraberim. Ama o giderse gene padişah lâzım” diyecek oldum, fena hâlde kızdı:”–Neden mutlaka padişah fikrine saplanıyorsun, Halil! diye bağırdı. Cumhuriyet yaparız”. Ben hemen elimi ağzına kapadım” (Egeli 1954: 34-35).
19 “Millet zulüm ve istibdâd altında mahvoluyor. Hürriyet olmayan bir memlekette ölüm ve izmihlâl vardır. Her terakkinin ve kurtuluşun anası hürriyettir. Tarih, bugün biz evlâtlarına bazı büyük vazifeler tahmil ediyor... Sizden fedakârlıklar bekliyorum. Kahhar bir istibdâda karşı ancak ihtilâl ile cevap vermek ve köhneleşmiş olan çürük idareyi yıkmak, milleti hâkim kılmak, hulâsa vatanı kurtarmak için sizi vazifeye davet ediyorum... Biz kuracağımız teşkilât ile bir gün mutlaka ve behemehal muvaffak olacağız. Vatanı, milleti kurtaracağız” (Cebesoy 1967: 96; Kızıldoğan 1937/I: 622).
20 Mustafa Kemal Selanik’te bir şubesini açtığı Vatan ve Hürriyet Cemiyeti’nde yakın arkadaşlarıyla hal-i hazıra dair yaptıkları konuşmalardan birinde; “İstibdada karşı bir ihtilâlle cevap vermek, köhnemiş çürük idareyi yıkmak ve milleti hâkim kılmak” ifadesini kullanmıştır. Bu ifade onun öteden beri millet hâkimiyetine dayalı bir devlet tesis etmek gereğini ortaya koymaktadır (İnan 1968).
21 Cumhuriyet, 18 Temmuz 1948.
22 Sadi Irmak bu hususu şu şekilde ele alır; “Gün gelecek şimdi hepinizin hayal sandığınız reformları ben gerçekleştireceğim. Sultanlık kaldırılmalıdır. Devletin yapısı mütecanis bir temele dayandırılmalıdır. Din ve devlet birbirinden ayrılmalıdır. Doğu medeniyetinden ayrılıp batı medeniyetine yönelmek zorundayız. Erkek ile kadın arasındaki farkı kaldırmalıyız. Böylece yeni bir toplum düzeni kurmalıyız. Batı uygarlığına girmemizi zorlaştıran yazıyı kaldırmalıyız. Latin Alfabesi’ni kabul etmeliyiz. Kıyafetimize kadar her noktada Batıya yönelmeliyiz. Emin olunuz ki bir gün bütün bu hedeflere ulaşacağız” (Irmak 1984: 5).
23 Mustafa Kemal’in yakın arkadaşlarından Kazım Özalp, Selanik’te geçen bu konuşmayı şu şekilde anlatır; “Mustafa Kemal ileride devlet kuracağız derdi. Seni harbiye nazırı yapacağım derdi bana. İzzeddin Çalışlar’a “Sen, erkân-ı harbiye-i umumiye reisi olacaksın” derdi. Selanik’ten arkadaşı olan Nuri Conker’e de: “Sen, iyi vali olursun.” derdi... gülüşürdük. Nuri Bey sorardı: “–Bizim ne olacağımızı anladık... Peki ya sen ne olacaksın?” “–Sizi tayin eden ne olursa o olacağım” derdi.” (Özalp 1963: 5; krş. Kılıç Ali 1955: 32-33; krş. Özalp 1974: 40-41).
24 Mustafa Kemal, bir gün Madam Hilda’ya; “–Türkiye’nin bu gidişi iyi değil, Türkiye’yi modern bir memleket yapmalı tıpkı Avrupa gibi. Bu memleketi baştan aşağı değiştirmeli, Allah nasib ederse günün birinde Türkiye’nin idaresinde rol sahibi olursam bilirim yapacağım yenilikleri…” (Gençosman-Banoğlu 1971: 247).
25 “İnşaallah padişahı alempenah efendimiz hazretlerinin sıhhat ve afiyetle ve her türlü kuyudat-ı ecnebiyyeden azade olarak taht-ı hümayyunlarında daim kalmasını eltaf-ı ilahiyyeden tazarru eylerim.” (Atatürk 1945: 61; Askerî Tarih Belgeleri Dergisi, Sene 30, Sayı 79, 1981, s. 23, 26, 29).
26 “Makam-ı hilafet ve saltanat herhangi bir şahsın değildir. Doğrudan doğruya bütün alemi İslam’ın müzaheretiyle beraber Türkiye halkındadır. O makam bizimdir. Muhafaza ettik ve nihayete kadar muhafaza edeceğiz…” (Gizli Celse Zabıtları, cilt I, içtima 3, 6.3.1938, s. 40). “Saltanat ve hilafeti hiçbir vakit başımızın üzerinden atamayız…” (Gizli Celse Zabıtları, cilt I, içtima 72, 25.9.1336, s. 137).
27 Mustafa Kemal, Misak-ı Millî’nin ilk müsveddelerini, Ocak 1920’de Ankara’da kaleme almıştır (Cebesoy 1989: 30, 53).
28 “Mustafa Kemal, Millî Misak’ın esaslarını, 1907’de tespit etmiş, vatanını tehlikeden kurtarmak için ne gibi çareler düşünüp bulduğunu cesaretle ortaya koymuştur.”
"""

# metni küçük harfe çevir
 metin = metin.lower()

# noktalama işaretlerini kaldır
 metin = re.sub(r"[^\w\s]", "", metin)

# kelimelere ayır
 kelimeler = metin.split()

# kelimeleri say
 sayim = Counter(kelimeler)

# en çok geçen 10 kelimeyi bul
 en_cok = sayim.most_common(10)

# sonuçları yazdır
 print("En çok geçen kelimeler:")
 for kelime, adet in en_cok:
    print(f"{kelime}: {adet}")
